import { NextResponse } from "next/server";

export const runtime = "edge";

const MOCK_STREAM_CONTENT = `
# AI Learning Roadmap: Full Stack Mastery

## Phase 1: Foundations (Weeks 1-4)
- **HTML5 & CSS3**: Semantic HTML, Flexbox, Grid.
- **JavaScript Deep Dive**: ES6+, Closures, Promises, Async/Await.
- **Git & GitHub**: Version control basics.

## Phase 2: Frontend Frameworks (Weeks 5-8)
- **React.js**: Components, Hooks, Context API.
- **Tailwind CSS**: Utility-first styling.
- **State Management**: Redux Toolkit or Zustand.

## Phase 3: Backend & Database (Weeks 9-12)
- **Node.js & Express**: RESTful APIs.
- **PostgreSQL**: Relational data modeling, SQL.
- **Prisma ORM**: Type-safe database access.

## Phase 4: Advanced Concepts (Weeks 13-16)
- **Next.js**: SSR, SSG, App Router.
- **Authentication**: JWT, NextAuth.js.
- **Deployment**: Vercel, Docker, CI/CD pipelines.

*Generated by LearnMatrix AI*
`;

export async function POST(req: Request) {
  try {
    const { topic, level } = await req.json();
    const apiKey = process.env.OPENAI_API_KEY;

    // Fallback to Mock Stream if no API Key
    if (!apiKey) {
      const encoder = new TextEncoder();
      const stream = new ReadableStream({
        async start(controller) {
          const chunks = MOCK_STREAM_CONTENT.split("");
          for (const chunk of chunks) {
            controller.enqueue(encoder.encode(chunk));
            await new Promise((resolve) => setTimeout(resolve, 15)); // Simulate typing effect
          }
          controller.close();
        },
      });

      return new Response(stream, {
        headers: { "Content-Type": "text/plain; charset=utf-8" },
      });
    }

    // Real OpenAI Call
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [
          {
            role: "system",
            content: "You are an expert coding mentor. Generate a detailed, markdown-formatted learning roadmap.",
          },
          {
            role: "user",
            content: `Create a ${level} level learning roadmap for ${topic}. Include phases and key topics.`,
          },
        ],
        stream: true,
      }),
    });

    if (!response.ok) {
      throw new Error("OpenAI API Error");
    }

    // Transform OpenAI Stream to Text Stream
    const encoder = new TextEncoder();
    const decoder = new TextDecoder();
    const stream = new ReadableStream({
      async start(controller) {
        const reader = response.body?.getReader();
        if (!reader) {
          controller.close();
          return;
        }

        try {
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;

            const chunk = decoder.decode(value);
            const lines = chunk.split("\n");

            for (const line of lines) {
              if (line.startsWith("data: ")) {
                const data = line.slice(6);
                if (data === "[DONE]") continue;

                try {
                  const json = JSON.parse(data);
                  const content = json.choices[0]?.delta?.content || "";
                  if (content) {
                    controller.enqueue(encoder.encode(content));
                  }
                } catch (e) {
                  // Ignore parse errors for partial chunks
                }
              }
            }
          }
        } finally {
          controller.close();
        }
      },
    });

    return new Response(stream, {
      headers: { "Content-Type": "text/plain; charset=utf-8" },
    });

  } catch (error) {
    console.error("AI Generation Error:", error);
    return NextResponse.json(
      { error: "Failed to generate roadmap" },
      { status: 500 }
    );
  }
}
